spring:
  datasource:
    url: jdbc:mysql://${prodDbIp}:3306/melon_prod?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${prodDbId}
    password: ${prodDbPw}
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
    hibernate:
      ddl-auto: none
logging:
  level:
    root: info
    com.ll.exam.com.ll.exam.melon_exam.app: info
    org.hibernate.type.descriptor.sql: info
custom:
  site:
    baseUrl: "https://domain"